### ISSUE TITLE
Halloween Candy Dispenser

### ISSUE THREAD

**Issue by isaacplmann** [bbarke/candy-dispenser#1]
Hi!

Our family would like to try to make your candy dispenser before October 28, 2020!  Could you share more details about the wiring?  What step motor did you use?  How did the wires connect?  My husband is a software programmer, but we're a bit weak in the electronics!

Thanks so much for the inspiration!

Best, 
Melanie Mann

**Comment by isaacplmann** [comment]
Also, how exactly did you build and install the tensioner?

**Comment by bbarke** [comment]
Hi there! I'm thrilled you would like to make one of these.
I updated the readme with the wiring diagram, and we will publish the drawings and the STLs for the various parts of the project on our website in the next day or two.

**Comment by bbarke** [comment]
Website is updated! Take a look at the drawings and parts list here: https://barkersrandomprojects.com/projects/candyDispenser

**Comment by isaacplmann** [comment]
Thanks!  I’ll take a look.
